# Generated by Django 6.0 on 2025-12-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='exercise_attempts',
            field=models.JSONField(default=list),
        ),
    ]
